/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import Controle.ControleAgenda;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Salvador Carlos
 */
public class Agenda extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jScrollPaneTabela = new javax.swing.JScrollPane();
        jTableTabela = new javax.swing.JTable();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelidade = new javax.swing.JLabel();
        jTextFieldIdade = new javax.swing.JTextField();
        jLabelTelefone = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();
        jLabelCorte = new javax.swing.JLabel();
        jComboBoxCorte = new javax.swing.JComboBox<>();
        jLabelPreco = new javax.swing.JLabel();
        jLabelMoeda = new javax.swing.JLabel();
        jComboBoxPreco = new javax.swing.JComboBox<>();
        jLabelData = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        jToggleButtonCadastrar = new javax.swing.JToggleButton();
        jToggleButtonRemover = new javax.swing.JToggleButton();
        jButtonLimpar = new javax.swing.JButton();
        jLabelFundoAgenda = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuBloquear = new javax.swing.JMenu();
        jMenuItemBloquear = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda - v0.1 BETA");
        getContentPane().setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Agenda");
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(840, 30, 110, 32);

        jTableTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Idade", "Telefone", "Corte", "Preço", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneTabela.setViewportView(jTableTabela);

        getContentPane().add(jScrollPaneTabela);
        jScrollPaneTabela.setBounds(0, 0, 710, 620);

        jLabelNome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setText("Nome");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(730, 200, 60, 19);
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(730, 230, 170, 40);

        jLabelidade.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelidade.setForeground(new java.awt.Color(255, 255, 255));
        jLabelidade.setText("Idade");
        getContentPane().add(jLabelidade);
        jLabelidade.setBounds(730, 280, 70, 19);
        getContentPane().add(jTextFieldIdade);
        jTextFieldIdade.setBounds(730, 310, 170, 40);

        jLabelTelefone.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelTelefone.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefone.setText("Telefone");
        getContentPane().add(jLabelTelefone);
        jLabelTelefone.setBounds(730, 370, 70, 19);
        getContentPane().add(jTextFieldTelefone);
        jTextFieldTelefone.setBounds(730, 400, 170, 40);

        jLabelCorte.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCorte.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorte.setText("Corte");
        getContentPane().add(jLabelCorte);
        jLabelCorte.setBounds(920, 200, 60, 19);

        jComboBoxCorte.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBoxCorte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Punk normal", "Juba", "Escovinha Fina", "Escovinha Grossa", "Carreca " }));
        getContentPane().add(jComboBoxCorte);
        jComboBoxCorte.setBounds(920, 230, 160, 40);

        jLabelPreco.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelPreco.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPreco.setText("Preco");
        getContentPane().add(jLabelPreco);
        jLabelPreco.setBounds(920, 280, 50, 19);

        jLabelMoeda.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelMoeda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMoeda.setText("Meticais");
        getContentPane().add(jLabelMoeda);
        jLabelMoeda.setBounds(1020, 310, 70, 40);

        jComboBoxPreco.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBoxPreco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "50", "40", "45", "15" }));
        getContentPane().add(jComboBoxPreco);
        jComboBoxPreco.setBounds(920, 310, 80, 40);

        jLabelData.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(255, 255, 255));
        jLabelData.setText("Data");
        getContentPane().add(jLabelData);
        jLabelData.setBounds(920, 370, 34, 15);
        getContentPane().add(jTextFieldData);
        jTextFieldData.setBounds(920, 400, 160, 40);

        jToggleButtonCadastrar.setBackground(new java.awt.Color(153, 255, 153));
        jToggleButtonCadastrar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jToggleButtonCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonCadastrar.setText("Agendar");
        jToggleButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonCadastrar);
        jToggleButtonCadastrar.setBounds(830, 470, 160, 40);

        jToggleButtonRemover.setBackground(new java.awt.Color(255, 51, 51));
        jToggleButtonRemover.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jToggleButtonRemover.setText("Remover");
        jToggleButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRemoverActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonRemover);
        jToggleButtonRemover.setBounds(920, 550, 160, 40);

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar);
        jButtonLimpar.setBounds(730, 550, 170, 40);

        jLabelFundoAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visual/imagens/fundoAgenda.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoAgenda);
        jLabelFundoAgenda.setBounds(-6, -25, 1130, 660);

        jMenuBloquear.setText("Bloquear");

        jMenuItemBloquear.setText("Bloquear");
        jMenuItemBloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBloquearActionPerformed(evt);
            }
        });
        jMenuBloquear.add(jMenuItemBloquear);

        jMenuBar.add(jMenuBloquear);

        jMenuSair.setText("Sair");

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar.add(jMenuSair);

        setJMenuBar(jMenuBar);

        setSize(new java.awt.Dimension(1113, 674));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //Variaveis 
    private String nome;
    private int idade;
    private int telefone;
    private String corte;
    private int preco;
    private String data;

    private void setCorte(String corte) {
        this.corte = corte;
    }

    private void setIdade(int idade) {
        this.idade = idade;
    }

    private void setData(String data) {
        this.data = data;
    }

    private void setNome(String nome) {
        this.nome = nome;
    }

    private void setTelefone(int telefone) {
        this.telefone = telefone;
    }

    private void setPreco(int preco) {
        this.preco = preco;
    }

    public int getTelefone() {
        return telefone;
    }
    ControleAgenda Controlagenda= new ControleAgenda();
    private void jMenuItemBloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBloquearActionPerformed
        // Bloquear
       if(Controlagenda.Bloquear()){
           dispose();
       }
    }//GEN-LAST:event_jMenuItemBloquearActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // Sair
        Controlagenda.Sair();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jToggleButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCadastrarActionPerformed
        // Cadastrar
        setNome(jTextFieldNome.getText());
        
        try{
        setIdade(Integer.parseInt(jTextFieldIdade.getText()));
        if(this.idade <=0){
           JOptionPane.showMessageDialog(null, "Idade inválida.");
        }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Insira uma idade válida!");
        }
        
        try{
        String tel = jTextFieldTelefone.getText();
        int telVerif = tel.length();
        if(telVerif == 9){
            setTelefone(Integer.parseInt(jTextFieldTelefone.getText()));
        }else if(telVerif !=9){
            JOptionPane.showMessageDialog(null, "Telefone Inválido.");
        }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Insira um telefone válido!");
        }
        
        setCorte(String.valueOf(jComboBoxCorte.getSelectedItem()));
        setPreco(Integer.parseInt(jComboBoxPreco.getSelectedItem().toString()));
        //Por melhorar
        setData(jTextFieldData.getText());
        
        DefaultTableModel tabela = (DefaultTableModel) jTableTabela.getModel();
        Object[] dados = {this.nome, this.idade, this.telefone, this.corte, this.preco, this.data};
        tabela.addRow(dados);
    }//GEN-LAST:event_jToggleButtonCadastrarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // Limpar
        jTextFieldNome.setText("");
        jTextFieldIdade.setText("");
        jTextFieldTelefone.setText("");
        jTextFieldData.setText("");
        
        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jToggleButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRemoverActionPerformed
        // remover
        if(jTableTabela.getSelectedRow() != -1){
            DefaultTableModel tabela = (DefaultTableModel) jTableTabela.getModel();
            tabela.removeRow(jTableTabela.getSelectedRow());
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha.");
        }
    }//GEN-LAST:event_jToggleButtonRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JComboBox<String> jComboBoxCorte;
    private javax.swing.JComboBox<String> jComboBoxPreco;
    private javax.swing.JLabel jLabelCorte;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelFundoAgenda;
    private javax.swing.JLabel jLabelMoeda;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelidade;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuBloquear;
    private javax.swing.JMenuItem jMenuItemBloquear;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JScrollPane jScrollPaneTabela;
    private javax.swing.JTable jTableTabela;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldIdade;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldTelefone;
    private javax.swing.JToggleButton jToggleButtonCadastrar;
    private javax.swing.JToggleButton jToggleButtonRemover;
    // End of variables declaration//GEN-END:variables

}
